
server:
  port: 8083
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      forece: true
      
spring:
   datasource:
      dirver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://172.30.1.50:3306/insight?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC 
      username: root
      password: haha5032
   servlet:
      multpart:
        max-file-size: 100MB
        max-request-size: 120MB